---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in blackbox_exporter_web_listen_address"
